Blog/blog/views.py
from flask import Blueprint,render_template,flash,redirect,url_for,request
from Blog.data_model.models import Post,Comment,Tag
from Blog.web_forms.comment_form import comment_form
from extension import db

blog_api = Blueprint('blog_api',__name__)
@blog_api.route('/<tag_id>')
def blog_view(tag_id):
    tag = Tag.query.all()
    page = request.args.get('page',1,type=int)
    if(tag_id == '0'):
        post = Post.query.paginate(page,3,False)
    else:
        post = Post.query.filter(Post.t_id == tag_id).paginate(page,3,False)
    return render_template('main_templates/blog.html',posts=post,tags=tag,current_tagid=tag_id)

@blog_api.route('/post/<post_id>',methods=['GET','POST'])
def post_view(post_id):
    tag = Tag.query.all()
    form = comment_form()
    post = Post.query.filter(Post.id == post_id).first()
    if form.validate_on_submit():
        comment = Comment(name=form.name.data,email=form.email.data,comment=form.comment.data,post=post)
        db.session.add(comment)
        db.session.commit()
        # flash(message=u'提交成功')
        return redirect(url_for('blog_api.post_view',post_id=post_id))
    return render_template('main_templates/single-post.html',post=post,form=form,tags=tag)

Blog/diary/views.py
from flask import Blueprint,render_template,request
from flask_login import login_required
from Blog.data_model.models import Tag,Diary
diary_api = Blueprint('diary_api',__name__)

@diary_api.route('/')
@login_required
def diary_view():
    tag = Tag.query.all()
    page = request.args.get('page', 1, type=int)
    diary = Diary.query.paginate(page, 3, False)
    return render_template('main_templates/diary.html',tags=tag,diarys=diary)

@diary_api.route('/<post_id>')
@login_required
def post_view(post_id):
    tag = Tag.query.all()
    post = Diary.query.filter(Diary.id == post_id).first()
    return render_template('main_templates/diary_single_post.html',tags=tag,post=post)

Blog/login/views.py
from flask import Blueprint,render_template,flash,redirect,url_for,request
from Blog.web_forms.login_form import LoginForm
from Blog.web_forms.register_form import register_form
from Blog.data_model.models import User
from extension import db
from flask_login import login_user,logout_user,login_required
login_api = Blueprint('login_api',__name__)

@login_api.route('/login',methods = ['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user,boolean_user = isuser(form.username.data,form.password.data)
        if boolean_user:
            login_user(user,form.remember_me.data)
            return redirect(request.args.get('next') or url_for('main_api.main_view'))
    return render_template('login_templates/login.html',form=form)

@login_api.route('/register',methods=['GET','POST'])
@login_required
def register():
    form = register_form()
    if form.validate_on_submit():
        user = User(form.username.data,form.email.data,form.password.data)
        db.session.add(user)
        db.session.commit()
        flash(message=u'注册成功，请登录')
        return redirect(url_for('login_api.login'))
    return render_template('login_templates/sign-up.html',form=form)

@login_api.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main_api.main_view'))

#判断是不是存在的用户
def isuser(username,password):
    user = User.query.filter(User.name==username).first()
    if user!=None:
        if user.check_password(password):
            return user,True
        else:
            flash(message=u'密码错误')
            return user,False
    else:
        flash(message=u'用户名不存在')
        return user,False

Blog/templates/Koiphotos_base.html
<html lang="zh-CN">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1024">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>照片墙</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='Koiphotos_static/css/style.css') }}">
</head>

<body class="impress-not-supported">

<div class="fallback-message">
    <p>The image wall is being generated, please wait... If the page didn't change after one minute, there must be
        something wrong about your browser, you better try this browser: <b>Chrome</b>, <b>Safari</b> or <b>Firefox</b>.
    </p>
</div>

<div id="blue-loader"></div>
<div id="mask-bg"></div>

<a class="button overview-btn" href="#overview">全景</a>
<a class="button about-btn" href="{{url_for('photos_api.upload')}}">上传</a>
<a class="button close-btn" href="{{ url_for('main_api.main_view')}}">
    <img src="{{ url_for('static', filename='Koiphotos_static/images/close.png') }}" width="30" height="30">
</a>
<input class="button" id="full-screen" type="image" src="{{ url_for('static', filename='Koiphotos_static/images/fullscreen.png') }}"
       width="25" onclick="toggleFullScreen()">
<input id="up" type="image" src="{{ url_for('static', filename='Koiphotos_static/images/up.png') }}" width="30" height="30">
<input id="down" type="image" src="{{ url_for('static', filename='Koiphotos_static/images/down.png') }}" width="30" height="30">

<div id="impress">
    <div id="image-container">
        {% block page_content %}{% endblock %}
        <div class="step" id="about" data-x="{{ overview[0] }}" data-y="{{ overview[1] }}" data-z="20000"
             data-rotate-x="90"
             data-rotate-z="180">
            <div class="center-text">
                <p class="big-text">My Word</p>
                <hr>
                <div class="small-text">
                    <p>Miss you a lot</p>
                    <br>
                </div>
                <br>
                <a class="shake shake-hard button donate-bt" href="#overview">Back</a>
            </div>
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='Koiphotos_static/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='Koiphotos_static/js/impress.js') }}"></script>
<script src="{{ url_for('static', filename='Koiphotos_static/js/imagesloaded.js') }}"></script>
<script src="{{ url_for('static', filename='Koiphotos_static/js/main.js') }}"></script>
<script>impress().init();</script>

</body>
</html>

Blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% block ck %}
{% endblock %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<title>KoiCarrot Space</title>

<link rel="stylesheet" href="{{url_for('static',filename='main_static/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename='main_static/css/font-awesome.min.css')}}">

<!-- Main css -->
<link rel="stylesheet" href="{{url_for('static',filename='main_static/css/style.css')}}">
<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">
</head>
<body>



<!-- PRE LOADER -->

<div class="preloader">
     <div class="sk-spinner sk-spinner-wordpress">
          <span class="sk-inner-circle"></span>
     </div>
</div>


<!-- Navigation section  -->
<div class="navbar navbar-default navbar-static-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>
               <a href="{{url_for('main_api.main_view')}}" class="navbar-brand"><img src="{{url_for('static',filename='main_static/images/carrot3.png')}}" height="80" width="160"></a>
          </div>

          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-right">
                    <li>
                         <div class="dropdown">
                              <button class="dropbtn">Koi技术</button>
                              <div class="dropdown-content">
                                   <a href="{{url_for('blog_api.blog_view',tag_id=0)}}">随便看看</a>
                                   {% for tag in tags %}
                                   <a href="{{url_for('blog_api.blog_view',tag_id=tag.id)}}">{{tag.name}}</a>
                                   {% endfor %}
                              </div>
                         </div>
                    </li>
                    <li></li>
                    <li><a href="https://aidn.jp/mikutap/">MikuTap</a></li>
                    {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('diary_api.diary_view')}}">Carrot日志</a></li>
                    <li><a href="{{url_for('photos_api.image_wall')}}">Pho图册</a></li>
                    <li><a href="{{url_for('login_api.logout')}}">登出</a></li>
                    {% else %}
                    <li><a href="{{url_for('login_api.login')}}">登陆</a></li>
                    {% endif %}
                    <li><a href="{{url_for('login_api.register')}}">注册</a></li>
               </ul>
          </div>

  </div>
</div>



<!-- Home Section -->
{% block home %}
{% endblock %}



<!-- Portfolio Section -->
{% block portfolio %}
{% endblock %}


<!-- Footer Section -->
<footer>
     <div class="container">
          <div class="row">


               <div class="col-md-3 col-sm-3">
                    <p>您可以邮件KoiCarrot@163.com联系我，我会在收到信息尽快回复</p>
               </div>


               <div class="clearfix col-md-12 col-sm-12">
                    <hr>
               </div>

               <div class="col-md-6 col-sm-6">
                    <div class="footer-copyright">
                         <p>KoiCarrot</p>
                    </div>
               </div>

               <div class="col-md-6 col-sm-6">
                    <ul class="social-icon">
                         <li><div> &copy; 2017 KoiCarrot.cn</div><a href="http://www.miitbeian.gov.cn/">粤ICP备17102134号</a></li>
                    </ul>
               </div>
               
          </div>
     </div>
</footer>



<!-- SCRIPTS -->

<script src="{{url_for('static',filename='main_static/js/jquery.js')}}"></script>
<script src="{{url_for('static',filename='main_static/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static',filename='main_static/js/custom.js')}}"></script>

</body>
</html>

Blog/templates/contact_formhelper.html
{% macro render_field(field) %}
<div>{{ field.label(class="sr-only")}}</div>
<div>{{ field(class="form-control",placeholder = field.id, autocomplete="off") }}
  {% if field.errors %}
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
  {% endif %}
</div>
{% endmacro %}

Blog/templates/formhelper.html
{% macro render_field(field) %}
<div>{{ field.label(class="sr-only")}}</div>
<div>{{ field(class="form-control",placeholder = field.id, autocomplete="off") }}
  {% if field.errors %}
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
  {% endif %}
</div>
{% endmacro %}