Blog/blog/views.py
from flask import Blueprint,render_template,flash,redirect,url_for,request
from Blog.data_model.models import Post,Comment,Tag
from Blog.web_forms.comment_form import comment_form
from extension import db

blog_api = Blueprint('blog_api',__name__)
@blog_api.route('/<tag_id>')
def blog_view(tag_id):
    tag = Tag.query.all()
    page = request.args.get('page',1,type=int)
    if(tag_id == '0'):
        post = Post.query.paginate(page,3,False)
    else:
        post = Post.query.filter(Post.t_id == tag_id).paginate(page,3,False)
    return render_template('main_templates/blog.html',posts=post,tags=tag,current_tagid=tag_id)

@blog_api.route('/post/<post_id>',methods=['GET','POST'])
def post_view(post_id):
    tag = Tag.query.all()
    form = comment_form()
    post = Post.query.filter(Post.id == post_id).first()
    if form.validate_on_submit():
        comment = Comment(name=form.name.data,email=form.email.data,comment=form.comment.data,post=post)
        db.session.add(comment)
        db.session.commit()
        # flash(message=u'提交成功')
        return redirect(url_for('blog_api.post_view',post_id=post_id))
    return render_template('main_templates/single-post.html',post=post,form=form,tags=tag)

Blog/diary/views.py
from flask import Blueprint,render_template,request
from flask_login import login_required
from Blog.data_model.models import Tag,Diary
diary_api = Blueprint('diary_api',__name__)

@diary_api.route('/')
@login_required
def diary_view():
    tag = Tag.query.all()
    page = request.args.get('page', 1, type=int)
    diary = Diary.query.paginate(page, 3, False)
    return render_template('main_templates/diary.html',tags=tag,diarys=diary)

@diary_api.route('/<post_id>')
@login_required
def post_view(post_id):
    tag = Tag.query.all()
    post = Diary.query.filter(Diary.id == post_id).first()
    return render_template('main_templates/diary_single_post.html',tags=tag,post=post)

Blog/templates/main_templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<title>Magnet - Minimal Portfolio Template</title>

<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/font-awesome.min.css">

<!-- Main css -->
<link rel="stylesheet" href="css/style.css">
<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">

</head>
<body>



<!-- PRE LOADER -->

<div class="preloader">
     <div class="sk-spinner sk-spinner-wordpress">
          <span class="sk-inner-circle"></span>
     </div>
</div>

<!-- Navigation section  -->

<div class="navbar navbar-default navbar-static-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>
               <a href="index.html" class="navbar-brand"><i class="fa fa-magnet"></i></a>
          </div>
          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-right">
                    <li><a href="index.html">Projects</a></li>
                    <li class="active"><a href="about.html">Our Studio</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="contact.html">Contact</a></li>
               </ul>
          </div>

  </div>
</div>


<!-- About Section -->

<section id="about">
     <div class="container">
          <div class="row">

               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="section-title">
                         <h3>about our story</h3>
                         <h2>The creative web & mobile studio and focused on brand identity, web development and social marketing.</h2>
                    </div>

                    <div class="col-md-8 col-sm-12">
                         <img src="images/about-image.jpg" class="img-responsive" alt="About">
                    </div>

                    <div class="col-md-4 col-sm-12">
                         <h1>Magnet Studio</h1>
                         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
                         <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
                    </div>

                    <div class="clearfix"></div>

                     <hr>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>

                    <hr>

                    <div class="col-md-4 col-sm-6">
                         <h3>Web Development</h3>
                         <ul>
                              <li>Online Shopping Site</li>
                              <li>Wordpress CMS</li>
                              <li>Bootstrap themes</li>
                              <li>Web Application</li>
                         </ul>
                    </div>

                    <div class="col-md-4 col-sm-6">
                         <h3>Brand Identity</h3>
                         <ul>
                              <li>Logo Design</li>
                              <li>Personal Branding</li>
                              <li>Flyer Design</li>
                              <li>Creative Direction</li>
                         </ul>
                    </div>

                    <div class="col-md-4 col-sm-6">
                         <h3>Social marketing</h3>
                         <ul>
                              <li>facebook, twitter.</li>
                              <li>Page Maintenance</li>
                              <li>Social media</li>
                         </ul>
                    </div>
               </div>

          </div>
     </div>
</section>

<!-- Footer Section -->

<footer>
     <div class="container">
          <div class="row">

               <div class="col-md-3 col-sm-3">
                    <i class="fa fa-magnet"></i>
               </div>

               <div class="col-md-4 col-sm-4">
                    <p>124 Market Street, Suite 3570 San Francisco, CA 3042 United States</p>
               </div>

               <div class="col-md-offset-1 col-md-4 col-sm-offset-1 col-sm-3">
                    <p><a href="mailto:youremail@gmail.com">hello@yourstudio.co</a></p>
                    <p>(+01) 2048937 / 02 203403</p>
               </div>

               <div class="clearfix col-md-12 col-sm-12">
                    <hr>
               </div>

               <div class="col-md-6 col-sm-6">
                    <div class="footer-copyright">
                         <p>© 2016 Magnet Studio | All Rights Reserved. More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p> 
                    </div>
               </div>

               <div class="col-md-6 col-sm-6">
                    <ul class="social-icon">
                         <li><a href="#" class="fa fa-facebook"></a></li>
                         <li><a href="#" class="fa fa-twitter"></a></li>
                         <li><a href="#" class="fa fa-linkedin"></a></li>
                    </ul>
               </div>
               
          </div>
     </div>
</footer>


<!-- SCRIPTS -->

<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/custom.js"></script>

</body>
</html>

Blog/templates/main_templates/blog.html
{% extends 'base.html' %}
<!-- Blog Section -->
{% block portfolio %}
<section id="blog">
     <div class="container">
          <div class="row">

               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="section-title">
                         <h3>Welcome To Tech-Blog</h3>
                         <h2>不定期更新</h2>
                    </div>
                    {% for post in posts.items %}
                    <div class="blog-post-thumb">
                         <div class="blog-post-title">
                              <h3><a href="single-post.html">{{post.title}}</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="{{post.user.icon}}" class="img-responsive img-circle">{{post.user.name}}</a></span>
                              <span><i class="fa fa-date"></i>{{post.time}}</span>
                              <span><a href="#"><i class="fa fa-comment-o"></i>{{post.comments|count}}</a></span>
                         </div>
                         <div class="blog-post-des">
                              <p>{{post.short_body}}</p>
                              <a href="{{url_for('blog_api.post_view',post_id=post.id)}}" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>
                    {% endfor %}
               </div>
          </div>
          <div class = "col-md-offset-1 col-md-10 col-sm-12">
               <div class = "blog-post-format">
                    {% if posts.has_prev %}
                    <span><a href="{{url_for('blog_api.blog_view',page=posts.prev_num,tag_id=current_tagid)}}">上一页</a></span>
                    {% endif %}
                    {% for post in posts.iter_pages(left_edge=1,left_current=2,right_current=2,right_edge=1) %}
                    {% if post==None %}
                    <span>...</span>
                    {% else %}
                    <span><a href="{{url_for('blog_api.blog_view',page=post,tag_id=current_tagid)}}">{{post}}</a></span>
                    {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                    <span><a href="{{url_for('blog_api.blog_view',page=posts.next_num,tag_id=current_tagid)}}">下一页</a></span>
                    {% endif %}
               </div>
               <span>当前页:{{posts.page}}</span>
          </div>
     </div>
</section>
{% endblock %}

Blog/templates/main_templates/contact.html
{% extends 'base.html' %}
{% block ck %}
{{ ckeditor.load() }}
{% endblock %}
<!-- Contact Section -->
{% block portfolio %}
<section id="contact">
     <div class="container">
          <div class="row">

               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="section-title">
                         <h3>联系</h3>
                         <h2>您可以在这里和我取得联系，期待您的宝贵意见</h2>
                    </div>
                    {% from 'contact_formhelper.html' import render_field %}
                    <form action="/contact" method="post">
                        {{ form.csrf_token }}
                        {{render_field(form.name)}}
                        {{ form.email_body }}
                        {% if form.email_body.errors %}
                            {% for error in form.email_body.errors %}
                                {{ error }}<br>
                            {% endfor %}
                        {% endif %}
                        <div class="col-md-3 col-sm-4">
                            <input type="submit" class="form-control" value="Send Message">
                        </div>
                    </form>
               </div>

          </div>
     </div>
</section>
{% endblock %}

Blog/templates/main_templates/diary.html
{% extends 'base.html' %}
<!-- Blog Section -->
{% block portfolio %}
<section id="blog">
     <div class="container">
          <div class="row">

               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="section-title">
                         <h3>Welcome To KoiCarrot Space</h3>
                         <h2>Everyone has a secret</h2>
                    </div>
                    {% for post in diarys.items %}
                    <div class="blog-post-thumb">
                         <div class="blog-post-image">
                              <a href="{{url_for('diary_api.post_view',post_id=post.id)}}">
                                   <img src="{{post.blog_image}}" class="img-responsive" alt="Blog Image">
                              </a>
                         </div>
                         <div class="blog-post-title">
                              <h3><a href="single-post.html">{{post.title}}</a></h3>
                         </div>
                         <div class="blog-post-format">
                              <span><a href="#"><img src="http://oz6fn6yv5.bkt.clouddn.com/Rabbit_Icon.jpg-user_icon" class="img-responsive img-circle">{{post.user.name}}</a></span>
                              <span><i class="fa fa-date"></i>{{post.time}}</span>
                         </div>
                         <div class="blog-post-des">
                              <p>{{post.short_body}}</p>
                              <a href="{{url_for('diary_api.post_view',post_id=post.id)}}" class="btn btn-default">Continue Reading</a>
                         </div>
                    </div>
                    {% endfor %}
               </div>
          </div>
          <div class = "col-md-offset-1 col-md-10 col-sm-12">
               <div class = "blog-post-format">
                    {% if diarys.has_prev %}
                    <span><a href="{{url_for('diary_api.diary_view',page=diarys.prev_num)}}">上一页</a></span>
                    {% endif %}
                    {% for post in diarys.iter_pages(left_edge=1,left_current=2,right_current=2,right_edge=1) %}
                    {% if post==None %}
                    <span>...</span>
                    {% else %}
                    <span><a href="{{url_for('diary_api.diary_view',page=post)}}">{{post}}</a></span>
                    {% endif %}
                    {% endfor %}
                    {% if diarys.has_next %}
                    <span><a href="{{url_for('diary_api.diary_view',page=diarys.next_num)}}">下一页</a></span>
                    {% endif %}
               </div>
               <span>当前页:{{diarys.page}}</span>
          </div>
     </div>
</section>
{% endblock %}

Blog/templates/main_templates/diary_single_post.html
{% extends 'base.html' %}
<!-- Blog Single Post Section -->
{% block portfolio %}
<section id="blog-single-post">
     <div class="container">
          <div class="row">
               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="blog-single-post-thumb">
                         <div class="blog-post-image">
                              <img src="{{post.blog_image}}" class="img-responsive" alt="Blog Image">
                         </div>

                         <div class="blog-post-title">
                              <h2>{{post.title}}</a></h2>
                         </div>
                         {% if post %}
                         <div class="blog-post-format">
                              <span><a href="#"><img src="http://oz6fn6yv5.bkt.clouddn.com/Rabbit_Icon.jpg-user_icon" class="img-responsive img-circle">{{post.user.name}}</a></span>
                              <span><i class="fa fa-date"></i>{{post.time}}</span>
                         </div>
                         {% endif %}
                         <div class="blog-post-des">
                              <p>{{post.body|safe}}</p>
                         </div>
                    </div>
          </div>
     </div>
</section>
{% endblock %}

Blog/templates/main_templates/index.html
{% extends 'base.html' %}
<!-- Home Section -->
{% block home %}
<section id="home">
     <div class="container">
          <div class="row">

               <div class="col-md-12 col-sm-12">
                    <h2>Every-thing will be all right.</h2>
                    <hr>
               </div>

          </div>
     </div>
</section>
{% endblock %}

<!-- Portfolio Section -->
{% block portfolio %}
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>
<section id="portfolio">
     <div class="container">
          <div class="row">

               <div class="col-md-4 col-sm-6">
                    <a href="{{url_for('blog_api.blog_view',tag_id=0)}}">
                         <div class="portfolio-thumb">
                              <img src="{{url_for('static',filename='main_static/images/portfolio-img1.jpg')}}" class="img-responsive" alt="Portfolio">
                                   <div class="portfolio-overlay">
                                        <div class="portfolio-item">
                                             <h3>技术</h3>
                                             <small>Tech change the world</small>
                                        </div>
                                   </div>
                         </div>
                    </a>
               </div>

               <div class="col-md-4 col-sm-6">
                    <a href="{{url_for('diary_api.diary_view')}}">
                         <div class="portfolio-thumb">
                              <img src="{{url_for('static',filename='main_static/images/portfolio-img2.jpg')}}" class="img-responsive" alt="Portfolio">
                                   <div class="portfolio-overlay">
                                        <div class="portfolio-item">
                                             <h3>日志</h3>
                                             <small>Happiness or Sadness</small>
                                        </div>
                                   </div>
                         </div>
                    </a>
               </div>

               <div class="col-md-4 col-sm-6">
                    <a href="{{url_for('photos_api.image_wall')}}">
                         <div class="portfolio-thumb">
                              <img src="{{url_for('static',filename='main_static/images/portfolio-img3.jpg')}}" class="img-responsive" alt="Portfolio">
                                   <div class="portfolio-overlay">
                                        <div class="portfolio-item">
                                             <h3>图册</h3>
                                             <small>All the memory</small>
                                        </div>
                                   </div>
                         </div>
                    </a>
               </div>

               <div class="col-md-4 col-sm-6">
                    <a href="https://aidn.jp/mikutap/">
                         <div class="portfolio-thumb">
                              <img src="{{url_for('static',filename='main_static/images/portfolio-img4.jpg')}}" class="img-responsive" alt="Portfolio">
                                   <div class="portfolio-overlay">
                                        <div class="portfolio-item">
                                             <h3>娱乐</h3>
                                             <small>Enjoy Yourself</small>
                                        </div>
                                   </div>
                         </div>
                    </a>
               </div>

               <div class="col-md-4 col-sm-6">
                    <a href="#">
                         <div class="portfolio-thumb">
                              <img src="{{url_for('static',filename='main_static/images/portfolio-img5.jpg')}}" class="img-responsive" alt="Portfolio">
                                   <div class="portfolio-overlay">
                                        <div class="portfolio-item">
                                             <h3>敬请期待</h3>
                                             <small>oops!</small>
                                        </div>
                                   </div>
                         </div>
                    </a>
               </div>

               <div class="col-md-4 col-sm-6">
                    <a href="#">
                         <div class="portfolio-thumb">
                              <img src="{{url_for('static',filename='main_static/images/portfolio-img6.jpg')}}" class="img-responsive" alt="Portfolio">
                                   <div class="portfolio-overlay">
                                        <div class="portfolio-item">
                                             <h3>敬请期待</h3>
                                             <small>oops!</small>
                                        </div>
                                   </div>
                         </div>
                    </a>
               </div>

          </div>
     </div>
</section>
{% endblock %}

Blog/templates/main_templates/single-post.html
{% extends 'base.html' %}
<!-- Blog Single Post Section -->
{% block ck %}
{{ ckeditor.load() }}
{% endblock %}
{% block portfolio %}
<section id="blog-single-post">
     <div class="container">
          <div class="row">
               <div class="col-md-offset-1 col-md-10 col-sm-12">
                    <div class="blog-single-post-thumb">
                         <div class="blog-post-image">
                              <img src="{{post.blog_image}}" class="img-responsive" alt="Blog Image">
                         </div>

                         <div class="blog-post-title">
                              <h2>{{post.title}}</a></h2>
                         </div>
                         {% if post %}
                         <div class="blog-post-format">
                              <span><a href="#"><img src="{{post.user.icon}}" class="img-responsive img-circle">{{post.user.name}}</a></span>
                              <span><i class="fa fa-date"></i>{{post.time}}</span>
                         </div>
                         {% endif %}

                         <div class="blog-post-des">
                              <p>{{post.body|safe}}</p>
                         </div>

                         <div class="blog-comment">
                              <h3>{{post.comments|count}}评论</h3>
                                   {% for comment in post.comments %}
                                   <div class="media">
                                        <div class="media-object pull-left">
                                             <img src="images/comment-image1.jpg" class="img-responsive img-circle" alt="Blog Image">
                                        </div>
                                        <div class="media-body">
                                             <h3 class="media-heading">{{comment.name}}</h3>
                                             <span>{{comment.email}}</span>
                                             <p>{{comment.comment|safe}}</p>
                                        </div>
                                   </div>
                                   {% endfor %}
                         </div>

                         <div class="blog-comment-form">
                              <h3>评论</h3>
                                   {% from "formhelper.html" import render_field %}
                                   <form action="/blog/post/{{post.id}}" method="post">
                                        {{ form.csrf_token }}
                                        {{render_field(form.name)}}
                                        {{render_field(form.email)}}
                                        {{ form.comment }}
                                        {% if form.comment.errors %}
                                             {% for error in form.comment.errors %}
                                                  {{ error }}<br>
                                             {% endfor %}
                                        {% endif %}
                                        <div class="col-md-3 col-sm-4">
                                             <input type="submit" class="form-control" value="Post Your Comment">
                                        </div>
                                   </form>
                         </div>
                    </div>
          </div>
     </div>
</section>
{% endblock %}